### ISSUE TITLE
Warning: DOMDocument::loadXML(): Empty string supplied as input in 

### ISSUE THREAD

**Issue by ciawebsite** [DeveloperCielo/Webservice-1.5-php#11]
Boa tarde.

Esta e minha primeira loja virtual e estou implementando pela primeira vez o mudulo da cielo e me deparei com o seguinte erro:

Warning: DOMDocument::loadXML(): Empty string supplied as input in C:\xampp\htdocs\cielo\Cielo\Serializer\TransactionResponseUnserializer.php on line 44

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'O número do pedido deve ter entre 1 e 20 caracteres' in C:\xampp\htdocs\cielo\Cielo\Order.php:136 Stack trace: #0 C:\xampp\htdocs\cielo\Cielo\Serializer\TransactionResponseUnserializer.php(96): Cielo\Order->setNumber(NULL) #1 C:\xampp\htdocs\cielo\Cielo\Serializer\TransactionResponseUnserializer.php(56): Cielo\Serializer\TransactionResponseUnserializer->readDadosPedido(Object(Cielo\Transaction)) #2 C:\xampp\htdocs\cielo\Cielo\Cielo.php(176): Cielo\Serializer\TransactionResponseUnserializer->unserialize(false) #3 C:\xampp\htdocs\cielo\index.php(27): Cielo\Cielo->transactionRequest(Object(Cielo\Transaction)) #4 {main} thrown in C:\xampp\htdocs\cielo\Cielo\Order.php on line 136

Creio que estou deixando passar alguma coisa. alguém pode me ajudar ?

**Comment by CentaurWarchief** [comment]
Acredito que a exceção seja bem clara em relação ao problema:
> O número do pedido deve ter entre 1 e 20 caracteres.

Dê uma verificada na chamada de `$cielo->order(...)`, veja as informações que estão sendo enviadas.

**Comment by ciawebsite** [comment]
eu andei verificando o código e percebi q a classe CurlOnlyPostHttpClient  retorna isso:

Cielo\Http\CurlOnlyPostHttpClient Object ( );

e acaba caindo em uma exception pois parece estar vazia.

**Comment by CentaurWarchief** [comment]
Certo, de fato, parece então que o problema está na resposta que volta da Cielo nas requisições, teria como você verificar como a transação foi criada e como está sendo retornado (XML)?

**Comment by ciawebsite** [comment]
Bom dia @CentaurWarchief me parece que o xml não chega a ser gerado pois o código para de executar antes disso (Posso estar errado pois comecei a trabalhar com essa api ontem e não tenho muito conhecimento de como ela funciona). Nos meus testes percebi que o código para de executar quando sendHttpRequest retorna vazia para a função unserialize. 

    private function sendHttpRequest($message)
    { 
        /* @var callable|OnlyPostHttpClientInterface $sendPostRequest */
        $sendPostRequest = $this->onlyPostClient;

         return $sendPostRequest(
            $this->endpoint,
            [
                'Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8',
                'Accept' => 'text/xml; charset=utf-8',
                'User-Agent' => 'PHP-SDK: 1.0'
            ],
            [
                'mensagem' => $message
            ]
        );
    }

A variável $mensagem chega ate esta função com o valor:

100699306925fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f345518700000001832018051123178142859910009862015-08-28T14:21:43PT0visa11http://localhost/cielo/index.php3true455187false 

E a $sendPostRequest retorna apenas isso:

Cielo\Http\CurlOnlyPostHttpClient Object ( )

**Comment by ciawebsite** [comment]
Problema resolvido.

Decidi fazer upload do código e tudo funcionou maravilhosamente.

testeTransaÃ§Ã£o autorizada com sucesso. TID=10069930693F28CA1001

O problema estava no servidor local.

**Comment by CentaurWarchief** [comment]
Sim, `$sendPostRequest` sempre irá retornar isso mês, é uma instância de `CurlOnlyPostHttpClient`, utilizada para fazer as requisições na Cielo.

**Comment by ciawebsite** [comment]
Muito obrigado por esclarecer minhas duvidas @CentaurWarchief

**Comment by paulocoghi** [comment]
Se está tudo ok, pode fechar a issue ;)

**Comment by CentaurWarchief** [comment]
@paulocoghi isso é com o @netojoaobatista, não sou da organização/tenho acesso ao repositório.

**Comment by paulocoghi** [comment]
Tranquilo ;) Esqueci de me dirigir ao @ciawebsite , que abriu a issue. Ele também pode fechar.

**Comment by CentaurWarchief** [comment]
Verdade!

**Comment by ciawebsite** [comment]
Muito obrigado pela ajuda amigos vou fechar a issue :)
