### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by aymone** [DeveloperCielo/Webservice-1.5-php#13]
Pessoal, a instalação pode ser feita com outras dependências do composer?

Ou devo rodar o composer apenas para a SDK?

Acontece que ela duplica algumas coisas que já tenho no projeto, como a pasta composer e phpunit.

Talvez seja ignorância minha, mas acho que facilitaria um pouco, ter um guia de instalação mais abrangente, for duumies.

O correto é adicionar a depedência no meu Composer.json ou  clonar via git e depois rodar o composer install?

**Comment by netojoaobatista** [comment]
Você pode adicionar junto às outras dependências no seu composer.

**Comment by aymone** [comment]
Acabei copiando a pasta Cielo para a vendors do meu projeto, mas acho que não fiz da melhor forma.
O problema mesmo é o Cake2 não usar namespaces. Aí preciso gerar um autoloader para ele carregar a sdk. Rodando o composer install, ele duplicou coisas que eu já tinha no Vendors. Mas dentro da pasta /webservice-1.5/ aonde originalmente estava a Cielo.

**Comment by aymone** [comment]
@netojoaobatista , como fica a chamada dele dentro do composer?

"developercielo/webservice": "1.5"

Tem como fazer algo assim?

**Comment by CentaurWarchief** [comment]
@aymone exatamente, ou: `composer require developercielo/webservice` já vai instalar a dependência e injetar a declaração no composer.json.

**Comment by pedrommone** [comment]
No caso ele está registrado no packagist como ´´´developercielo/webservice-1.5-php´´´.

**Comment by aymone** [comment]
Ao chamar:
```
$ composer require developercielo/webservice
```

Retorna:

```
 [InvalidArgumentException]                                                   
  Could not find package developercielo/webservice at any version for your mi  
  nimum-stability (stable). Check the package spelling or your minimum-stabil  
  ity 
```

**Comment by aymone** [comment]
Obrigado!
