### ISSUE TITLE
Bug na definição do produto "Débito"

### ISSUE THREAD

**Issue by davicrystal** [DeveloperCielo/Webservice-1.5-php#14]
Olá Amigos,

Existe um bug que não permite a definição do código de produto "Débito" ("A"). No arquivo Webservice-1.5-php/src/Cielo/Serializer/TransactionResponseUnserializer.php, linha 113, o parâmetro "(int)" transforma sempre o retorno do método $this->getValue(...) como inteiro, tornando assim impossível a definição do código do produto como "A" (Débito). 

Retirando o parâmetro (int) é necessário alterar a validação da varável "$product" em Webservice-1.5-php/src/Cielo/PaymentMethod.php na linha 93, pois a comparação é absoluta, diferenciando o tipo da variável (numeral e texto), sendo que um XML é enviado ao webservice, esse tipo de comparação é desnecessária, pois não há tal tipo de diferenciação em um XML, permitindo assim, na validação, a substituição dos operadores "===" por "==".

**Comment by netojoaobatista** [comment]
Você está correto, @davicrystal.

Falha minha ao forçar o cast para inteiro. Vou corrigir isso.
