### ISSUE TITLE
Parcelamento (Loja e Administradora [com juros])

### ISSUE THREAD

**Issue by jozephbrasil** [DeveloperCielo/Webservice-1.5-php#16]
Como faço para diferenciar o tipo de parcelamento? Se é Administradora (com juros) ou Loja? Não consegui localizar na documentação.

**Comment by netojoaobatista** [comment]
@jozephbrasil, o SDK foi atualizado para adicionar suporte ao parcelamento via administradora.

Por favor, faça um git pull e, então, utilize a constante `PaymentMethod::PARCELADO_ADM`;
