### ISSUE TITLE
Melhorias no Cancelletion

### ISSUE THREAD

**Issue by jozephbrasil** [DeveloperCielo/Webservice-1.5-php#21]
Como não posso commitar no código, sugestões:

Class CancellationInformation:

- Alterar getValue and setValue para getAmount and setAmount;

Class Cancellation:

- Permitir definir o valor para cancelamento, conforme documentação;

**Comment by netojoaobatista** [comment]
@jozephbrasil, você pode contribuir com o código sim:

1. Faça um fork do projeto.
2. Faça commit no seu fork.
3. Faça push para o seu remote.
4. Faça um pull request.

Quando fizer o PR, eu receberei a notificação com suas melhorias no código e, se tudo estiver okay, farei a mesclagem no repositório principal. A vantagem de seguir esse processo é que você será automaticamente listado como contribuidor do projeto. Veja só: [Contributors to DeveloperCielo/Webservice-1.5-php](https://github.com/DeveloperCielo/Webservice-1.5-php/graphs/contributors)

:smile:
