### ISSUE TITLE
Exemplo amplo de autenticação

### ISSUE THREAD

**Issue by nerijunior** [DeveloperCielo/Webservice-1.5-php#25]
Seguindo o exemplo sugerido para criação de transação fico em dúvida sobre o diagrama que consta na seção "Autenticação e nível de segurança" solicitando que o usuário acesse uma segunda url para autenticação.

Pelo que compreendi o processo deve ser assim:

1. Criar a transação e verificar o código LR
  1.1 Se LR = 0 -> Transação criada com sucesso ( sem nenhum erro)
  1.2 Se LR != 0 -> Existe algum problema na transação
  1.3 Tratar Exceptions

2. Se LR = 0 e consta url de autenticação, envio o usuário para essa URL para um processo "manual" de autenticação.
  2.1 - Efetuar consulta no TID para verificar se a transação ocorreu com sucesso.

3. Se LR = 0 mas a url de autenticacao não foi informada, efetuo uma consulta na TID da transação e devolvo para o usuário o resultado

Se esse fluxo estiver correto, existe algo bem estranho pois quando solicito uma compra com o código de um cartão MASTERCARD MAESTRO, mas na transação envio bandeira como VISA DEBITO ele retorna LR = 0 com url de autenticação, porém as consultas futuras ao TID informado só retornam com status = 1.

Poderiam me explicar se é assim mesmo, se não compreendi o fluxo ou dar uma melhorada nos exemplos?

**Comment by netojoaobatista** [comment]
@nerijunior,

A segunda URL para autenticação é responsabilidade da Cielo; para que a autenticação ocorra, você deve enviar a tag `<autorizar>` com valor igual a 1, que significa *Autorizar se autenticado*, ou com valor igual a 0, que significa *Apenas autenticar*.

Utilizando o SDK, ficaria assim:

```php
<?php
require 'vendor/autoload.php';

use Cielo\Cielo;
use Cielo\CieloException;
use Cielo\Transaction;
use Cielo\Holder;
use Cielo\PaymentMethod;

$cielo = new Cielo('1006993069', '25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3', Cielo::TEST);

$holder = $cielo->holder('4012001037141112', 2018, 5, Holder::CVV_INFORMED, 123);
$order = $cielo->order('178148599', 1000);
$paymentMethod = $cielo->paymentMethod(PaymentMethod::VISA, PaymentMethod::CREDITO_A_VISTA);

$transaction = $cielo->transaction($holder,
                                   $order,
                                   $paymentMethod,
                                   'http://localhost/cielo.php',
                                   Transaction::AUTHORIZE_IF_AUTHENTICATED,
                                   true);
```

Veja que na criação da transação foi utilizado `Transaction::AUTHORIZE_IF_AUTHENTICATED`. Logo após configurar a transação, você deverá enviar a requisição para a Cielo:

```php
try {
    $transaction = $cielo->transactionRequest($transaction);
    $authenticationUrl = $transaction->getAuthenticationURL();

    if (!empty($authenticationUrl)) {
        // redireciona o cliente parai a URL de autenticação
    }
} catch (CieloException $e) {
    printf("Opz[%d]: %s\n", $e->getCode(), $e->getMessage());
}
```

**Comment by nerijunior** [comment]
@netojoaobatista 

Eu preciso de todas as possibilidades de pagamento ( incluindo débito ), estou enviando `Transaction::AUTHORIZE` e o capture como `true`, estou usando o código da mesma maneira como você informou na resposta, porém ocorre que se o usuário informa um cartão inválido, não estou obtendo essa resposta, isso está relacionado com `$authorize` que estou enviando?

**Comment by netojoaobatista** [comment]
Sim. O `Transaction::AUTHORIZE` é para autorização direta **sem** autenticação. Para que tenha autenticação, você deve informar `Transaction::AUTHORIZE_IF_AUTHENTICATED` ou `Transaction::ONLY_AUTHENTICATE`.

Um descritivo sobre todas as possibilidades, com detalhes de como devem ser configurados, pode ser encontrado no manual, na seção [Operações e Configurações](https://developercielo.github.io/Webservice-1.5/#operações-e-configurações)

**Comment by nerijunior** [comment]
@netojoaobatista Agora compreendi o problema! Muito obrigado pelas rápidas respostas.

**Comment by nerijunior** [comment]
@netojoaobatista uma última dúvida, existem cartões que podem não tem autenticação?

**Comment by netojoaobatista** [comment]
Sim, existe. Mas acho mais fácil responder sua dúvida de forma invertida. Hoje a autenticação funciona apenas para cartões Visa e MasterCard que foram emitidos pelos seguintes bancos:

* Visa
    * Bradesco
    * Banco do Brasil
    * Santander
    * Itaú
    * Citibank

* MasterCard
    * Bradesco
    * Banco do Brasil
    * Santander
    * Itaú
    * Citibank
    * BRB
    * Caixa

**Comment by aymone** [comment]
Como você fazem para saber se deve ou não realizar a autenticação?

Se for MasterCard do Nubank por exemplo, como saberia se devo autenticar?

**Comment by netojoaobatista** [comment]
@aymone,

Toda transação com cartão de debito precisa de autenticação.

Para transações de credito, porém, a autenticação é facultativa, ou seja, a loja escolhe se quer autenticar. Mas não é recomendado pois acaba causando um impacto processo de conversão da venda por dificultar a experiência de compra do cliente.

**Comment by aymone** [comment]
@netojoaobatista Obrigado pela resposta.

É possível usar débito pelo webservice? Como se dá a autenticação pelo cliente?
Realmente não encontrei esta informação detalhada.

**Comment by netojoaobatista** [comment]
Sim, @aymone , é possível utilizar débito via WS.

A criação de transações é exatamente igual ao crédito e os detalhes sobre a formatação do XML podem ser encontrados no manual, na seção [Criando Transações](https://developercielo.github.io/Webservice-1.5/#criando-transações).

Para especificar que se trata de um cartão de débito, basta informar, no nó [forma-de-pagamento](https://developercielo.github.io/Webservice-1.5/#forma-pagamento), o valor **A** para o produto.

Informações sobre a autenticação podem ser encontradas na seção [Autenticação e nível de segurança](https://developercielo.github.io/Webservice-1.5/#autenticação-e-nível-de-segurança)

**Comment by aymone** [comment]
Até aí está ok @netojoaobatista.

Porém quando efetuo testes com débito, recebo o seguinte erro:
```
Cielo: Obrigatório o envio dos campos CAVV e XID  Code: 86
```
Já conseguiu testar débito no ambiente de testes?

**Comment by aymone** [comment]
Pelo que entendi do link que você mandou, é possível fazer, mas é necessário efetuar alguns redirects entre a cielo, a instituição bancária e voltar a loja... Grato.

**Comment by guizizin** [comment]
Ola bom dia pessoal, meu plugin de pagamento Cielo para VIRTUEMART 2.0 funcinou perfeitamente desde 2012 porem agora me deparei com um problema na autenticação, já tentei na Cielo mais de 10 vezes eles não me auxiliam nem ajudam, perguntei vários amigos programadores porem ninguém dispos a me ajudar, gostaria de saber se existe aí alguma alma boa que poderia me auxiliar a ajustar meu plugin de pagamento obrigado


MENSAGEM DE ERRO:

![erro](https://user-images.githubusercontent.com/33533896/32660879-ccd8bd82-c60b-11e7-8e85-1af2420cf998.jpg)

        Erro ao autenticar: 10382059536KS1OPVGMB 95130605 1706 986 2017-11-10T07:27:18 PT visa 1 1 1 1 Transacao sem autenticacao 2017-11-10T11:27:19.060-02:00 1706 https://www.meucheckout.com.br/transactionalvnext/order/buypage/e825ed67-5aa2-4c6e-ac43-7d77ceea3b7d

        TRANSAÇÃO CIELO N. 0

        Verifique em seu e-mail o extrato desta transação.

se alguem puder me nortear neste código agradeço
