### ISSUE TITLE
Utilização do nome do portador do cartão nas transações

### ISSUE THREAD

**Issue by rpraes** [DeveloperCielo/Webservice-1.5-php#27]
No arquivo ecommerce.xsd existe o elemento "nome-portador", porém não encontrei em nenhum lugar esse atributo sendo setado na classe TransactionRequestSerializer.

Esse atributo não esta sendo mais utilizado no webservice?

**Comment by netojoaobatista** [comment]
Esse campo não é obrigatório, @rpraes.

**Comment by rpraes** [comment]
@netojoaobatista, mas se eu utilizar o método $holder->setName('Teste'), ele não deveria preencher esse elemento "nome-portador" no xml gerado? Mesmo não sendo obrigatório?

**Comment by netojoaobatista** [comment]
Você está correto, @rpraes.

O FIX já foi providenciado.

**Comment by ederlopes** [comment]
A implementação acima já foi feita? estou com a mesma dúvida...

**Comment by rafaelpatro** [comment]
Seu código está correto.
O portal da Cielo é que não exibe esse campo. Eu envio o _portador_ há tempo, e nunca tive acesso a esse campo no portal da Cielo, ou em qualquer relatório fornecido pela Cielo.

Acho que eles sequer validam esse campo. O usuário pode escrever qualquer nome, que não fará diferença pra Cielo.

**Comment by netojoaobatista** [comment]
Esse campo é opcional. Ele pode ser usado se também houver uma integração com anti-fraude. Do contrário, esse campo é meramente informativo.

**Comment by ederlopes** [comment]
Obrigado pela Resposta Rafael e Neto....porém Neto mesmo sendo opcional quando informado como eu fiz ele não deveria montar o no de dados do cliente e mandar para a CIELO...bom fica a sugestão...já estou acompanhando há atualização que vc postou para o a versão 3.0 porém esta dando o seguinte erro na url do sendbox.

Could not resolve host: sandbox.cieloeCommerce.cielo.com.br

se puder me ajudar ficaria agradecido, e parabéns pelo Trabalho Neto já acompanho-o o seu trabalho a bastante tempo aqui e no imasters

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://sandbox.cieloeCommerce.cielo.com.br/1/sales/",
  CURLOPT_RETURNTRANSFER => false,
  CURLOPT_CUSTOMREQUEST => "POST",
   CURLOPT_POSTFIELDS => "{\"MerchantOrderId\":\"2014111703\",\"Customer\":{\"Name\":\"Comprador Teste\"},\"Payment\":{\"Type\":\"CreditCard\",  \"Amount\":15700,  \"Installments\":1,  \"CreditCard\":{   \"CardNumber\":\"4551870000000183\", \"Holder\":\"Teste Holder\", \"ExpirationDate\":\"12/2021\", \"SecurityCode\":\"123\", \"Brand\":\"Visa\"}}}",
  CURLOPT_HTTPHEADER => array(
	"cache-control: no-cache",
	"content-type: application/json",
	"merchantid: 3aa754e8-8de2-45b8-82d6-da3979a911e4",
	"merchantkey: DGKNWHSWVUHKRTAFWOEWWGQOOOKYBEUQJKNILKTZ",
  ),
));

**Comment by netojoaobatista** [comment]
> Could not resolve host: sandbox.cieloeCommerce.cielo.com.br

Tem um erro no nome, por isso está tendo problemas de resolução. Ajuste o nome para:

[sandbox.cieloecommerce.cielo.com.br](https://sandbox.cieloecommerce.cielo.com.br)

Mas essa sua questão é **offtopic** nesse repositório. Se sua questão é sobre a 3.0, você deve fazê-la no repositório apropriado para evitar confusão aqui no repositório da 1.5.
