### ISSUE TITLE
Geração de Token (Cartão de Crédito)

### ISSUE THREAD

**Issue by rpraes** [DeveloperCielo/Webservice-1.5-php#28]
Estou tentando gerar um token associado a um cartão de crédito. Está funcionando normalmente, porém estou com uma dúvida:

Na documentação está informando que não é necessário enviar os dados do pedido para gerar um token, mas se eu setar um objeto Order vazio ou com os valores nulos, o método retorna uma exceção.

Qual o procedimento correto para gerar um token? Não faz muito sentido eu enviar as informações do valor do pedido, já que as futuras autorizações e capturas para este token podem ter valores diferentes.

**Comment by davicrystal** [comment]
Estava para abrir um ticket com a mesma questão. A documentação realmente diz que é possível gerar um token sem um "pedido", porém, pelo que eu vi no projeto atual, isso não é possível. Você confirma @netojoaobatista ?

**Comment by netojoaobatista** [comment]
@rpraes e @davicrystal, 

O SDK atualmente só suporta a geração do token através de uma requisição de transação. De fato, é possível, via API, fazer uma requisição só para gerar o token, mas esse suporte ainda não foi adicionado ao SDK.

Para gerar apenas o token, o XML da requisição deve ser assim:

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<requisicao-token id="8fc889c7-004f-42f1-963a-31aa26f75e5c" versao="1.2.1">
  <dados-ec>
    <numero>1234</numero>
    <chave>xxxx</chave>
  </dados-ec>
  <dados-portador>
    <numero>4012001038443335</numero>
    <validade>201508</validade>
    <nome-portador>FULANO DA SILVA</nome-portador>
  </dados-portador>
</requisicao-token>
```

**Comment by jozephbrasil** [comment]
Uma importante implementação no SDK.
