### ISSUE TITLE
Senha - POS

### ISSUE THREAD

**Issue by jozephbrasil** [DeveloperCielo/Webservice-1.5-php#29]
Existe alguma forma de capturar a senha, exatamente como a maquininha do PagSeguro faz? Para transações de crédito e débito, mas sem que seja redirecionado para um site? Aceitar, por exemplo, cartão com chip.

**Comment by netojoaobatista** [comment]
@jozephbrasil, me desculpe, mas não compreendi o que você quer fazer.

Você está transacionando utilizando um POS e quer pegar a senha do cliente? Porque crédito via web não é pedido senha do cliente; a única situação onde é pedido a autenticação, é no débito, por medida de segurança.

**Comment by jozephbrasil** [comment]
@netojoaobatista na verdade estou querendo montar uma POS muito parecido com o que o PagSeguro oferece. Aquela maquina Moderninha do PagSeguro, é exatamente uma idêntica.

**Comment by netojoaobatista** [comment]
Compreendido. Mas a senha é uma coisa muito pessoal do usuário. Por que você quer essa informação numa maquininha?

**Comment by jozephbrasil** [comment]
Para transacionar com chip e senha, da mesma forma que pagseguro e mercadopago fazem.

**Comment by netojoaobatista** [comment]
@jozephbrasil, a máquina que você se referindo, é essa aqui: https://www.cielo.com.br/solucoes-de-pagamentos/todas-as-solucoes-para-celular.html

**Comment by jozephbrasil** [comment]
Sim, é a mesma máquina.

**Comment by netojoaobatista** [comment]
E ela não atende ao seu propósito, @jozephbrasil?
