### ISSUE TITLE
Obter transações por intervalo de datas

### ISSUE THREAD

**Issue by TiagoGouvea** [DeveloperCielo/Webservice-1.5-php#32]
Procurei na documentação e no código e não encontrei.

Obter as transações em um determinado intervalo de datas, e retorna-los para utilização da aplicação.

Existe este recurso em algum lugar?

**Comment by netojoaobatista** [comment]
Não há essa funcionalidade no Webservice 1.5. Você consegue apenas fazer consultas utilizando o TID ou, em último caso, como contingência, utilizando o número do pedido.

**Comment by TiagoGouvea** [comment]
Ok. Como obter pelo numero do pedido, também não encontrei.

**Comment by netojoaobatista** [comment]
Pelo número do pedido não foi implementado no SDK porque não é recomendado fazer a consulta por esse número. A recomendação é que utilize o TID, que é um identificador único da transação.

**Comment by TiagoGouvea** [comment]
Ok. Perdi as notificações com os TIDs no log, só tenho os números dos pedidos e o intervalo de datas. O que sugere?

**Comment by netojoaobatista** [comment]
Nesse caso, acredito que sua situação pode ser descrita como questão de contingência. 

A mensagem de consulta pelo número de pedido é assim:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<requisicao-consulta-chsec id="a51489b1-93d5-437f-bb4f-5b932fade248" versao="1.2.1">
    <numero-pedido>1663784368</numero-pedido>
    <dados-ec>
        <numero>1006993069</numero>
        <chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave>
    </dados-ec>
</requisicao-consulta-chsec>
```

Você envia o número do pedido na plataforma da loja para consulta através do elemento `numero-pedido`.

**Comment by TiagoGouvea** [comment]
Excelente. Grato.
