### ISSUE TITLE
Captura parcial da transação

### ISSUE THREAD

**Issue by Thyoity** [DeveloperCielo/Webservice-1.5-php#34]
Preciso que seja adicionada o parâmetro "valor" na função createCaptureRequest() do arquivo CaptureRequestSerializer.php

Isso porque estou montando um e-commerce que lida com valores variáveis de peso.
Estou criando uma autorização e depois preciso capturar um valor parcial, e não total da transação.

**Comment by netojoaobatista** [comment]
Você mesmo pode adicionar, @Thyoity. Faça o clone do repositório, faça a alteração que precisa diretamente no código e, caso tenha interesse, faça um pull request que se estiver tudo certinho, mesclamos aqui no repositório.
