### ISSUE TITLE
Pedindo a validade no Request via token

### ISSUE THREAD

**Issue by vmatteus** [DeveloperCielo/Webservice-1.5-php#37]
Tive um problema ao tentar passar transações com o token, usando a api. Ao passar o holder somente com o token, a resposta era: "String value '' does not match pattern for type of validade element in DadosCartao...". Editei no TransactionRequestSerializer, pra quando a validade estiver vazia, não enviar. Este é um problema conhecido? Fica a sugestão/melhoria para analise. Abs

**Comment by jhonnymakis** [comment]
@vmatteus Estou com o mesmo problema:
Mensagem: O XML informado nÃ£o Ã© valido: - string value '' does not match pattern for type of validade element in DadosCartao in namespace http://ecommerce.cbmp.com.br: '' 

Quando fui na classe TransactionResponseUnserializer e tentei debugar o codigo sem querer mantando a verificacao, a transação foi aprovada;

       if (($code = $this->xpath->query('/c:erro/c:codigo')->item(0)) !== null) {
            $message = $this->xpath->query('/c:erro/c:mensagem')->item(0)->nodeValue;

            throw new CieloException($message, $code->nodeValue);
        }

@vmatteus Como você resolvel? Poderia disponibilizar o código ?

**Comment by jhonnymakis** [comment]
Eu coloquei uma verificação, para verificar se tem token, caso tenha não processar essa condição que informei.

**Comment by vmatteus** [comment]
Oi Jhonny,

Resolvi da mesma forma. Vamos ver se eles ajustam.

Abs

Vinícius Mautone Matteus


2016-05-06 17:27 GMT-03:00 Jhonny Makis <notifications@github.com>:
