### ISSUE TITLE
Status diferentes no Webservice e na Cielo.com.br

### ISSUE THREAD

**Issue by jarjar123** [DeveloperCielo/Webservice-1.5-php#4]
Olá!
Tenho uma transação que não sai do status _0 - Criada_, e não consigo cancelá-la.
A transação foi criada no dia 11/07, com a flag de autorização ativa (opção 2).
Até o momento a consulta retorna status _Criada_.
Ao solicitar o cancelamento, retorna erro `042 - Cancelamento da transação [tid='XXXXXXXX0000035CAA' não foi efetuado com sucesso.`

Ao acessar o painel administrativo www.cielo.com.br, a transação aparece como _Não Autorizada_.

O que pode estar ocorrendo?
Como faço para ter o retorno atualizado do webservice?

_Preciso registrar o cancelamento da transação em meu sistema, e não faço ideia de como lidar com isso. Por padrão meu sistema cancela registros com transações "Canceladas" ou "Não Autorizadas" apenas._

Alguma sugestão de como tratar essa situação?
Obrigado, e boa semana!

**Comment by fabioginzel** [comment]
Tentou ligar no suporte da cielo? Até agora eles sempre resolveram meus problemas....

**Comment by jarjar123** [comment]
Sim. O suporte informou _...não é possível cancelar uma transação “Não autorizada”_.
Enviaram por e-mail aquele fluxograma dos status, que está no manual de integração.

**Comment by netojoaobatista** [comment]
@jarjar123, o cancelamento significa, exatamente, cancelar uma autorização. Se não houve uma autorização, não há o que cancelar.

**Comment by jarjar123** [comment]
Mas o status _Criada_ deixa a possibilidade de ainda autorizarem ou desautorizarem a transação. Certo?! Ou não. Posso cancelar sem medo qualquer transação exceto _Autorizada_?

**Comment by jarjar123** [comment]
Desculpe, acho que não fui claro: Posso descartar __em meus sistema__ qualquer compra cuja transação possui status _Criada_?
Não há possibilidade da Cielo prosseguir essa transação?
