### ISSUE TITLE
Transação via TOKEN

### ISSUE THREAD

**Issue by jhonnymakis** [DeveloperCielo/Webservice-1.5-php#42]
Quando faz uma transação via TOKEN fica pedindo: 
Número da ordem, data da ordem e idioma... 
Sempre cai no exception da class Order

Tentei passar de várias formas e não funcionava, ao fazer o processamento com os dados do cartão funciona normal.

No servidor de teste sempre funciona com token ou cartão, mas no servidor de produção não.

**Comment by netojoaobatista** [comment]
Se no ambiente de testes funciona, então você deve entrar em contato com a Cielo para verificar se o serviço está habilitado para seu estabelecimento comercial.

**Comment by jhonnymakis** [comment]
Para resolver o problema eu tirei o processamento dessa API e coloquei para enviar via XML e CURL.
A API não funciona bem quando é processamento via TOKEN.

**Comment by netojoaobatista** [comment]
Não compreendi seu último post. Pode elaborar?

**Comment by jhonnymakis** [comment]
As transações via TOKEN estão OK na CIELO.

Utilizando este (Webservice-1.5-php) eu não consigo finalizar o processamento utilizando TOKEN pois   ele fica procurando por alguns elementos do XML que não existem, tenta validar alguns campos que também não existem  no retorno do XML da CIELO, ou não foram passados pois estava enviado o pagamento via TOKEN.

Como este WebService não funcionar bem com o processamento via TOKEN, eu fiz o processamento utilizando XML puro e enviando via CURL mesmo;

Fiz também o reembolso parcial, que não achei disponível neste WebService.

**Comment by netojoaobatista** [comment]
Compreendido; mas se conseguiu fazer as transações na Cielo, é isso que importa. Se já está funcionando, vou fechar a issue.

**Comment by jhonnymakis** [comment]
Ok!
