### ISSUE TITLE
Bandeiras

### ISSUE THREAD

**Issue by jozephbrasil** [DeveloperCielo/Webservice-1.5-php#43]
Surgiu uma dúvida, será que alguém poderia ajudar?
No PaymentMethod existem apenas:

            PaymentMethod::VISA,
            PaymentMethod::MASTERCARD,
            PaymentMethod::DINERS,
            PaymentMethod::DISCOVER,
            PaymentMethod::ELO,
            PaymentMethod::AMEX,
            PaymentMethod::JCB,
            PaymentMethod::AURA,

Como adicionar outras bandeiras como AGIPLAN, BANESCARD, CABAL?

Outra coisa, como faço para diferenciar JCB CRED / ESPLANADA da JCB / VISA?

**Comment by netojoaobatista** [comment]
Constantes do PHP são meramente strings; basta informar a string de uma bandeira aceita pela Cielo.

Sobre a diferenciação das bandeiras, você pode fazer a validação através do algorítimo luhn e utilizar o BIN para fazer a identificação. Mas isso deve ser implementado por você; além disso, a lista de BINs das bandeiras não é muito definida, ou seja, você poderá ter vários "falsos positivos" e "falsos negativos". Não é recomendado utilizar essa validação como critério para aceitação dos pagamentos.

**Comment by jozephbrasil** [comment]
Mas a dúvida é se essas strings precisa ser um valor válido no webservice da Cielo. Se eu colocar HIPER, por exemplo, e a Cielo esperar que o valor passado seja HIPERCARD, vai dar erro?

**Comment by ederlopes** [comment]
Bom dia jozephbrasil vi que na issue 21 você estava perguntando sobre o processo de transação como cartão de débito, gostaria de saber se você conseguiu implantar, quais são os passos estou com a seguinte mensagem de erro: "Obrigatório o envio dos campos CAVV e XID" já li o manual e algumas respostas aqui dizendo que precisa passar o CCV mais ele esta sendo passado pode me ajudar?

**Comment by netojoaobatista** [comment]
Como eu disse, @jozephbrasil, basta informar uma bandeira aceita pela Cielo.

A lista de bandeiras suportadas está descrita no manual, na seção [Produtos e Bandeiras Suportadas](https://developercielo.github.io/Webservice-1.5/#produtos-e-bandeiras-suportadas)

**Comment by ederlopes** [comment]
Bom dia Neto, obrigado pela resposta estou passando uma bandeira visa normalmente porém o erro persiste...eu estou vendo que precisa submeter uma transação para autenticação, como faço isso utilizando a biblioteca disponibilizada, pois na documentação não mostra processo de autenticação, como fazer?

**Comment by netojoaobatista** [comment]
O fluxo é descrito na documentação; veja: [Autenticação e nível de segurança](https://developercielo.github.io/Webservice-1.5/#autenticação-e-nível-de-segurança)

**Comment by ederlopes** [comment]
OK obrigado...

**Comment by jozephbrasil** [comment]
@netojoaobatista Excelente. mas o problema é que precisamos habilitar o Hipercard e essa bandeira não está presente lá... :-D

**Comment by netojoaobatista** [comment]
Se não está presente é porque a bandeira não é suportada. Como essa não é uma questão técnica, o ideal é entrar em contato com o comercial da Cielo.

**Comment by ederlopes** [comment]
@netojoaobatista  não há como vocês colocarem um exemplo de transação com cartão de debito, como tem das outras no readme.md ?

**Comment by ederlopes** [comment]
Boa tarde pessoa depois de alguns testes consegui fazer a transação e capturar ela com a modalidade via DEBITO, segue abaixo o código funcional, só trocar as variáveis e pronto.

@netojoaobatista  verifique a viabilidade de colocar este código de exemplo de transação com cartão de debito no readme.md. 

Tenho certeza que será de grande valia para outros desenvolvedores...

$cielo 				= new Cielo($mid, $key, Cielo::TEST);
		$holder 			= $cielo->holder($cartao, $ano, $mes, Holder::CVV_INFORMED, $ccv);

		$order 				= $cielo->order( '2099001', 100);
		$paymentMethod 		= $cielo->paymentMethod('visa', 'A', 1);
		$transaction 		= $cielo->transaction(  $holder,
													$order,
													$paymentMethod,
													'http://localhost/retorno.php',
													Transaction::AUTHORIZE_IF_AUTHENTICATED,
													true);
		$transaction 			= $cielo->transactionRequest($transaction);
		$transaction->getAuthenticationURL();
		$strRedirectUrl = $transaction->getAuthenticationURL();
		
//Redirecione o usuario via javascript
  echo '<script type="text/javascript">	window.location.href = "' . $strRedirectUrl . '"	 </script>';
//ou via PHP
header("Location: $strRedirectUrl");

**Comment by jozephbrasil** [comment]
Massa que você conseguiu. Eu ainda não. Agora me diz uma coisa, como você captura o retorno? Tipo assim, o que é enviado nessa url localhost/retorno.php? Tem como você colocar aqui o que é repassado pra essa URL?

**Comment by netojoaobatista** [comment]
Estou reabrindo a issue porque a pergunta é interessante.

:smile:

**Comment by ederlopes** [comment]
@jozephbrasil é repassado um post para a pagina de retorno eu dei um var_dump($_POST) e vi que tem um campo com o nome TID, pegue este campo e faça uma requisição de consulta e cheque se o status da transação foi aprovado


$cielo = new Cielo($convenio_cielo->nu_convenio, $convenio_cielo->no_chave, Cielo::PRODUCTION);

		$consultation = $cielo->consultation($_POST['TID']); //tid da transação

		try {

			$consultationResponse = $cielo->consultationRequest($consultation);

			var_dump($consultationResponse);
			//$arrayStatusTransacao 	= $this->getStatusTransacao($transaction, $compra_credito, $this->nu_pedido_convenio);

		} catch (CieloException $e) {

			printf("Opz[%d]: %s\n", $e->getCode(), $e->getMessage());

		}

**Comment by Srkl** [comment]
@ederlopes Estou implementando a solução de débito e havia tentado exatamente o mesmo sugerido por você. No entanto minha página de callback não está recebendo nenhum valor através do $_POST. 

O var_dump está retornando array(0) { } 

Alguma luz do motivo?

Segue o trecho de código que estou testando

`$cielo = new Cielo($mid, $key, Cielo::TEST);

$holder = $cielo->holder('4518700000001832', 2018, 5, Holder::CVV_INFORMED, 123);
$order = $cielo->order('178148599', 100000);
$paymentMethod = $cielo->paymentMethod(PaymentMethod::VISA, PaymentMethod::DEBITO, 1);

$transaction = $cielo->transaction($holder,
                                   $order,
                                   $paymentMethod,
                                   'http://localhost/ws/callback.php',
                                   Transaction::AUTHORIZE_IF_AUTHENTICATED,
                                   true);

  try {

    $transaction = $cielo->transactionRequest($transaction);
    
    $authenticationUrl = $transaction->getAuthenticationURL();

    if (!empty($authenticationUrl)) {
        // redireciona o cliente parai a URL de autenticação
	header('Location: ' . $authenticationUrl);
	die();
    }

      if ($transaction->getAuthorization()->getLR() == 0)
          printf("Transação autorizada com sucesso. TID=%s\n", $transaction->getTid());

  } catch (CieloException $e) {

      printf("Opz[%d]: %s\n", $e->getCode(), $e->getMessage());

  } catch (Exception $e) { 
	var_dump($e);
  }`

**Comment by netofire** [comment]
Implementei o cartão de débito e ainda estou no período de testes. O único problema até então é que a Cielo não autentica o cliente (o suporte telefônico informou isso). Ou seja, não dá pra finalizar o teste em ambiente de testes. O fluxo que eu entendi foi:

Cliente finaliza o pedido > Sistema submete os dados à Cielo 
Cielo devolve o TID e uma URL para redirecionamento > Sistema redireciona browser do cliente
A Cielo redireciona o cliente (após o processo concluído) para a URL informada na requisição
Como eu já tenho o TID armazenado, na URL que o cliente acessa no final eu realizo a consulta e vejo que fim levou a transação

O problema: o status desse tipo de transação sempre retorna como 1 (em andamento), mas o processo ocorre sem erros pelo menos

**Comment by Srkl** [comment]
@netofire Mesma coisa aqui. Eu vou seguir esse mesmo caminho. 

1 - Criar a transação e guardar o TID 
2 - Passar o numero do pedido como parâmetro na URL de retorno.  
3 - Na página de retorno consultar a transação através do parâmetro, assim terei o TID para consultar o status dela. 

O grande problema é que no ambiente de desenvolvimento o status continua como 1

**Comment by ederlopes** [comment]
Boa tarde pessoal, @Srkl seguinte o processo de Debito com a Cielo no ambiente de desenvolvimento não é completo no meu ponto de vista. Como existe a necessidade de redirecionar para o banco emissor do cartão eles não fazem isso então não temos o post de retorno como eu mencionei em outros posts, porém quando o sistema esta em ambiente de produção O POST é enviado como informado anteriormente.

Sugiro mandar a URL de retorno como o @netofire falou é bem interessante, porém eu encontrei mais uma falha (Obs: acredito que seja uma falha), não consigo checar se a transação foi Autenticada pela CIELO, tive que colocar na Classe Cielo\Consultation.php

no final da classe 

public function getAuthentication()
    {
        return $this->authentication;
    }

$consultationResponse->getStatus() == 3 //transação não autenticada 

para saber as diversas mensagens de retorno para o usuário 

ai consultar $consultationResponse->getAuthentication()->getMessage() para saber a msg..

Lembre-se neste caso de Debito é fundamental saber se a Transação foi autenticada não é autorizada, porque na maioria das vezes os outros objetos virão nulos...e só o de autenticação vira preenchido.

**Comment by netofire** [comment]
Eu testei com um número que retornou status 3 (não autenticada), dentre aqueles números de teste do manual (era Visa, acho que o 4012001038443335 - 123 - 05/2018). 
Além do status 1 é o único status que consegui gerar.

**Comment by ederlopes** [comment]
não vai autenticar porque não tem validação do banco há não ser que tenha um cartão especifico para isso que eu não vi na documentação para fazer isso...

**Comment by PHPVulnerable** [comment]
Eder, conseguiu fazer? estou com um probleminha, estou usando o  if ($transaction->getAuthorization()->getLr()==0) porém parece que algumas não autorizam e pra mim aparece que autorizou, como posso resolver isso?
