### ISSUE TITLE
Obrigatório o envio dos campos CAVV e XID

### ISSUE THREAD

**Issue by ederlopes** [DeveloperCielo/Webservice-1.5-php#44]
Estou tentando fazer uma transação de DEBITO e esta aparecendo o erro acima. Existe algum exemplo de transação para DEBITO?

Meu código esta assim

$holder = $cielo->holder('4012001037141112', 2018, 5, Holder::CVV_INFORMED, 123);
		$order = $cielo->order('178148599', 1000);
		$paymentMethod = $cielo->paymentMethod(
			PaymentMethod::VISA,
			PaymentMethod::DEBITO
		);

		$transaction = $cielo->transaction(
			$holder,
			$order,
			$paymentMethod,
			'http://localhost/cielo.php',
			Transaction::AUTHORIZE_IF_AUTHENTICATED,
			true
		);

		try {
			$transaction = $cielo->transactionRequest($transaction);
			$authenticationUrl = $transaction->getAuthenticationURL();

			var_dump($authenticationUrl);

			if (!empty($authenticationUrl)) {
				// redireciona o cliente parai a URL de autenticação
			}
		} catch (CieloException $e) {
			printf("Opz[%d]: %s\n", $e->getCode(), $e->getMessage());
		}

**Comment by lelopes** [comment]
Estou com o mesmo erro. Esse erro apareceu quando coloquei o parcelamento Loja, produto = 'A'. Procurei no manual do webservice para ver algo a respeito mas só encontrei em códigos de erros. Gostaria de saber do que se trata os campos campos CAVV e XID para poder sanar o erro. Grato.

**Comment by ederlopes** [comment]
@lelopes  faz como esta descrito abaixo que vai funcionar depois de muito esforço saiu,,,,

$cielo = new Cielo($mid, $key, Cielo::TEST);
$holder = $cielo->holder($cartao, $ano, $mes, Holder::CVV_INFORMED, $ccv);

    $order              = $cielo->order( '2099001', 100);
    $paymentMethod      = $cielo->paymentMethod('visa', 'A', 1);
    $transaction        = $cielo->transaction(  $holder,
                                                $order,
                                                $paymentMethod,
                                                'http://localhost/retorno.php',
                                                Transaction::AUTHORIZE_IF_AUTHENTICATED,
                                                true);
    $transaction            = $cielo->transactionRequest($transaction);
    $transaction->getAuthenticationURL();
    $strRedirectUrl = $transaction->getAuthenticationURL();

//Redirecione o usuario via javascript
echo '';
//ou via PHP
header("Location: $strRedirectUrl");

**Comment by lelopes** [comment]
@ederlopes obrigado. Estou fazendo com xml nativo igual do manual, não estou usando a biblioteca php.
