### ISSUE TITLE
Obrigatório o envio dos campos CAVV e XID: XML

### ISSUE THREAD

**Issue by lelopes** [DeveloperCielo/Webservice-1.5-php#45]
Quando informo que o Parcelamento é : Parcelamento Loja, o produto = 'A' conforme manual, tenho retorno Obrigatório o envio dos campos CAVV e XID. Fui no manual do web-service e não encontrei referência sobre esses dois campos. Gostaria de saber a respeito desses dois campos para composição do XML.

**Comment by netojoaobatista** [comment]
@lelopes, o produto `A` é para débito.

**Comment by netojoaobatista** [comment]
De fato, Isso está descrito no manual: https://developercielo.github.io/Webservice-1.5/#forma-pagamento

**Comment by lelopes** [comment]
@netojoaobatista obrigado, desculpe a falta de atenção. Realmente A é débito.
