### ISSUE TITLE
Código dos Erros

### ISSUE THREAD

**Issue by Srkl** [DeveloperCielo/Webservice-1.5-php#46]
Estou implementando alguns cenários de erro para validar a implementação. Para isso estou usando a seguinte tabela como referencia https://developercielo.github.io/Webservice-1.5/#códigos-de-erros 

Logo de cara o WS me retornou um código diferente ao que esta descrito na tabela. 
Utilizei os seguintes dados do Cartão:

[holder:Cielo\Transaction:private] => Cielo\Holder Object
        (
            [creditCardNumber:Cielo\Holder:private] => 123456789012345
            [expiration:Cielo\Holder:private] => 202610
            [cvvIndicator:Cielo\Holder:private] => 1
            [cvv:Cielo\Holder:private] => 1234
            [holderName:Cielo\Holder:private] => 
            [token:Cielo\Holder:private] => 
        )

[order:Cielo\Transaction:private] => Cielo\Order Object
        (
            [number:Cielo\Order:private] => ORD57766E5DB56B7
            [total:Cielo\Order:private] => 25000
            [currency:Cielo\Order:private] => 986
            [dateTime:Cielo\Order:private] => 2016-07-01T10:21:33
            [description:Cielo\Order:private] => 
            [language:Cielo\Order:private] => PT
            [shipping:Cielo\Order:private] => 
            [softDescriptor:Cielo\Order:private] => 
        )

[paymentMethod:Cielo\Transaction:private] => Cielo\PaymentMethod Object
        (
            [issuer:Cielo\PaymentMethod:private] => visa
            [product:Cielo\PaymentMethod:private] => 2
            [installments:Cielo\PaymentMethod:private] => 8
        )

O retorno obtido foi:

Opz[17]: O Código de Segurança enviado é Inválido.

Na tabela de erros o código 17 diz "Código de segurança ausente". Além disso eu notei que o WS está aprovando qualquer número de cartão, com qualquer validate e qualquer código de segurança.

Imagino que não deverá ser um problema em produção, mas essas diferenças me confundiram bastante aqui por não gerar os erros esperados.

**Comment by netojoaobatista** [comment]
No ambiente de testes, o cartão não passa pelo autorizador de fato; por isso que é aceito números e datas de cartão "aleatórios". Sobre os códigos, houveram várias mudanças recentemente nesses códigos; consulte novamente o manual porque agora temos uma seção para códigos de retorno e uma outra para códigos de autorização.

:smile:
