### ISSUE TITLE
PaymentMethod::DEBITO

### ISSUE THREAD

**Issue by raphaieu** [DeveloperCielo/Webservice-1.5-php#49]
Boa tarde, estou com uma dúvida...

Fiz todo o processo correto com o pagto via débito, porém, eu imaginei que fosse abrir uma tela (ou redirecionar) para a tela do banco, a pessoa fazer o login e tal e retornar para a minha URL onde eu pudesse recuperar os dados... mas isso não acontece, alguém poderia me dá uma luz?

**Comment by netojoaobatista** [comment]
O SDK não faz - e nem poderia fazer - o redirecionamento porque isso depende da forma como sua aplicação funciona; tudo o que o SDK faz é a comunicação com a API. Você poderá pegar a URL de autenticação com o método de interface `Transaction::getAuthenticationUrl()`.

**Comment by raphaieu** [comment]
Valeu!
