### ISSUE TITLE
validação do XSD

### ISSUE THREAD

**Issue by marcospereda** [DeveloperCielo/Webservice-1.5-php#50]
oi, boa tarde !
desde já agradeço pela sua ajuda e espero não estar perguntando nenhuma bobagem, é que realmente não consigo fazer funcionar o primeiro exemplo de transação.
O primeiro problema que encontrei foi que dava "erro 500, não consegue atender a esta solicitação no momento." debugando encontrei o erro na função serialize do arquivo TransactionRequestSerializer, o arquivo ecommerce.xsd tem que estar na mesma pasta da minha página. 

Depois de copiar ele começou a dar erro de validação do xml ao rodar esta linha 

```php
$document->schemaValidate('ecommerce.xsd');
```
 
Utilizando https://github.com/hazardland/debug.php consegui ver o erro : 

"3033 - Element '{http://www.w3.org/2001/XMLSchema}sequence': The content is not valid. Expected is (annotation?, (element | group | choice | sequence | any)*). "

que pesquisando mais um pouco me levou a uma página falando que o problema estava com o xsd :http://stackoverflow.com/questions/13195605/xml-schema-xsd-file-error. 

eu também comparei o xml gerado com o xml da documentação https://developercielo.github.io/Webservice-1.5/#transação, notei que a versão é diferente e que alguns campos como a taxa de embarque, no gerado por mim está com valor zero e no mostrado no exemplo está vazio

versao="1.3.0"
contra 
versao="1.2.1"

> "< taxa-embarque >0</taxa-embarque>"
> contra 
> "< taxa-embarque/>"

 

abaixo segue o codigo que básicamente é o exemplo de transação utilizando os dados de cartão visa sem autenticação , https://developercielo.github.io/Webservice-1.5/#testes-e-homologação,  

```php
require 'vendor/autoload.php';

use Cielo\Cielo;
use Cielo\CieloException;
use Cielo\Transaction;
use Cielo\Holder;
use Cielo\PaymentMethod;

$mid = '1006993069'; //seu merchant id
$key = '25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3'; //sua chave

$cielo = new Cielo($mid, $key, Cielo::TEST);

$holder = $cielo->holder('4012001038443335', 2018, 5, Holder::CVV_INFORMED, 123);

$order = $cielo->order('178148599', 1000);

$paymentMethod = $cielo->paymentMethod(PaymentMethod::VISA, PaymentMethod::CREDITO_A_VISTA);

$transaction = $cielo->transaction($holder,
                                   $order,
                                   $paymentMethod,
                                   'http://www.sisalu.com.br',
                                   Transaction::AUTHORIZE_WITHOUT_AUTHENTICATION,
                                   true );

		
			   
  try {
    $transaction = $cielo->transactionRequest($transaction);

	
      if ($transaction->getAuthorization()->getLR() == 0)
          printf("Transação autorizada com sucesso. TID=%s\n", $transaction->getTid());

  } catch (CieloException $e) {


      printf("Opz[%d]: %s\n", $e->getCode(), $e->getMessage());

  }
```

mais uma vez agradeço pela ajuda,

Marcos

**Comment by netojoaobatista** [comment]
O erro 500 é um erro temporário; ainda está com problemas?

**Comment by marcospereda** [comment]
obrigado, o progamador já resolveu
