### ISSUE TITLE
Operação Débito

### ISSUE THREAD

**Issue by dinhoguitars** [DeveloperCielo/Webservice-1.5-php#52]
Bom dia!

Estou usando o SDK para fazer uma operação de Débito, quando faço o redirect para autenticação, a pagina do "Banco" para autenticação nao aparece

 Cielo cielo = new Cielo(ConfigApp.mid, ConfigApp.key, ConfigApp.UrlCieloEcommerce);

            Holder holder = cielo.holder("4012001037141112", "2018", "05", "123");
            holder.name = "Fulano Portador da Silva";
            
            Random randomOrder = new Random();

            Order order = cielo.order(randomOrder.Next(1000, 10000).ToString(), 10000);
            PaymentMethod paymentMethod = cielo.paymentMethod(PaymentMethod.VISA, PaymentMethod.DEBITO);
                        
            try
            {                    
                Transaction transaction = cielo.transactionRequest(
                                              holder,
                                              order,
                                              paymentMethod,
                                              ConfigApp.UrlRetornoAPP,
                                              Transaction.AuthorizationMethod.ONLY_AUTHENTICATE,
                                              true
                                          );
                                
                Response.Redirect(transaction.authenticationUrl);

**Comment by netojoaobatista** [comment]
@dinhoguitars, esse repositório aqui é do SDK PHP; por favor, reabra sua dúvida no repositório do SDK que você está utilizando.
