### ISSUE TITLE
Valor total do pedido faz com que a transação fique negada

### ISSUE THREAD

**Issue by victor0402** [DeveloperCielo/Webservice-1.5-php#57]
Primeiramente, estou em ambiente de testes.
Criei os dados do cartão e do pedido conforme o exemplo no readme, com algumas modificações pro meu cenário:
```
//...
$cielo = new Cielo(CieloLocal::MERCHANT_ID_TEST, CieloLocal::KEY_TEST, Cielo::TEST);
$holder = $cielo->holder('4551870000000183', 2018, 5, Holder::CVV_INFORMED, 123);

//R$ 59,43
$order = $cielo->order($pedido['pedido_id'], 5943);

$paymentMethod = $cielo->paymentMethod(PaymentMethod::VISA, PaymentMethod::CREDITO_A_VISTA);
$transaction = $cielo->transaction($holder,
				$order,
				$paymentMethod,
				null,
				Transaction::AUTHORIZE_WITHOUT_AUTHENTICATION,
				true);
$transaction = $cielo->transactionRequest($transaction);

$lrCode = $transaction->getAuthorization()->getLR();
//...
```

O valor da variável `$lrCode` está vindo sempre como 43 ("Transação não autorizada. Cartão bloqueado por roubo.").

Se eu mudo o valor do pedido para R$ 59,00:
`$order = $cielo->order($pedido['pedido_id'], 5900);`
A transação é autorizada e o LR obtido é o 0 (Transação autorizada com sucesso.).

Como faço para enviar esse valor R$ 59,43 sem dar o erro acima?

**Comment by jhernandes** [comment]
Olá Victor,

A API de testes funciona desta forma mesmo. No caso os centavos replicam os erros da seguinte tabela: https://developercielo.github.io/Webservice-1.5/#códigos-de-autorização-lr

Dependendo do valor enviado será simulado um resultado diferente.

Abraço

**Comment by victor0402** [comment]
Obrigado @jhernandes 

Agora fez sentido. Não sei se passou despercebido por mim, mas não encontrei nada sobre isso na documentação da API. Seria legal se isso estivesse mais claro na documentação.

**Comment by netojoaobatista** [comment]
@victor0402, [está na documentação](https://developercielo.github.io/Webservice-1.5/#dados-para-testes), veja:

> O valor do pedido além de seguir o formato sem pontos ou vírgulas decimais, deve terminar em “00”, caso contrário, a autorização será sempre negada. Exemplo: R$ 15,00 deve ser formatado como “1500”.

**Comment by victor0402** [comment]
@netojoaobatista 
Verdade! Valeu pela informação.

O que ainda não está claro na documentação é que os centavos determinam o código LR que vai ser retornado, conforme o @jhernandes explicou.

Sabendo disso agora vai facilitar muito os meus testes para cada tipo de resposta.

**Comment by netojoaobatista** [comment]
Você tem razão, @victor0402; vou providenciar a melhora dessa seção da documentação.
