### ISSUE TITLE
campo msgLoja

### ISSUE THREAD

**Issue by helder1983** [DeveloperCielo/Webservice-1.5-php#58]
olá. estou tentando informar o campo msgLoja. mas quando passo <br> para pular, conforme a documentação da cielo, o boleto exibe literalmente os caracteres <br>.
se informo o \n, na parte de cima do boleto a mensagem aparece corretamente, mas na parte de baixo ele ignora o salto de linha. é necessário algum outro parametro para isso?

**Comment by netojoaobatista** [comment]
Qual API está usando, @helder1983?

**Comment by helder1983** [comment]
seria a versão? é a 1.5

**Comment by netojoaobatista** [comment]
@helder1983, não existem esses campos na 1.5. Qual documentação você está usando para boleto?
