### ISSUE TITLE
Teste de validação Luhn

### ISSUE THREAD

**Issue by lucaspanik** [DeveloperCielo/Webservice-1.5-php#60]
A Cielo coloca em seu guia de boas práticas a importância do teste de Luhn, a classe possui algum método de validação de cartões de crédito semelhante ou igual ao Luhn?

**Comment by netojoaobatista** [comment]
Não. A responsabilidade pela validação do cartão é do desenvolvedor.

**Comment by lucaspanik** [comment]
Ata, obrigado pela atenção, achei esse link da Cielo que ajuda nessa validação.
[https://developercielo.github.io/Boas-praticas-de-ecommerce/#validação-no-backend](url)
