### ISSUE TITLE
Submeter Repositório ao Packagist

### ISSUE THREAD

**Issue by drupalista-br** [DeveloperCielo/Webservice-1.5-php#8]
Olá,

Eu pesquisei por este repositório em https://packagist.org e não encontrei. Caso já esteja lá, por favor me passe a url.

Caso ainda não esteja, peço por favor que disponibilize este repositório no https://packagist.org. O procedimento para submeter o repositório é:

* Acesse https://packagist.org/profile para copiar o Token ( Vc pode logar no Packagist com as credencias do Github, caso ainda não tenha uma conta lá );
* Acesse https://github.com/DeveloperCielo/Webservice-1.5-php/settings/hooks, adicione o Packagist em "Services", informe o Token e salve o formulário.
* Acesse https://packagist.org/packages/submit e submeta o link https://github.com/DeveloperCielo/Webservice-1.5-php

Obrigado.

**Comment by netojoaobatista** [comment]
@drupalista-br, pacote submetido.

[Webservice-1.5-php](https://packagist.org/packages/developercielo/webservice-1.5-php)
