### ISSUE TITLE
PHP Error DOMDocument::loadXML(): Empty string supplied as input

### ISSUE THREAD

**Issue by davicrystal** [DeveloperCielo/Webservice-1.5-php#9]
Olá Amigos,

Estou implementando a solução Webservice 1.,5 utilizando o SDK disponibilizada, em um projeto de e-commerce que por sua vez trabalha com Yii Framework. Estou em ambiente de testes, utilizando os dados disponíveis na documentação https://developercielo.github.io/Webservice-1.5/#chave-de-testes. O problema que ocorre é um erro quando invoco o método "transactionRequest", como segue abaixo:

$objTransactionResult = $objCielo->transactionRequest($objTransaction);

Obtenho o seguinte erro de PHP:

PHP Error: DOMDocument::loadXML(): Empty string supplied as input (/var/www/ecommerce/protected/components/gateways/CieloWebservice/src/CieloFiles/Serializer/TransactionResponseUnserializer.php:44)

Analisando o arquivo TransactionResponseUnserializer.php verifiquei que o erro ocorre devido a resposta totalmente vazia vinda do webservice Cielo. Para efeito de teste, realizei o dump da variável $transaction que é enviada para o webservice na linha 172 do arquivo "Cielo.php", o resultado segue abaixo. Como o problema trata-se de um erro dentro da SDK e não gerou um "exception" acredito que talvez possa tratar-se de um bug.

- Dump da variável $transaction que é enviada para o webservice na linha 172 do arquivo Cielo.php:

object(Cielo\Transaction)#338 (18) {
  ["tid":"Cielo\Transaction":private]=>
  NULL
  ["pan":"Cielo\Transaction":private]=>
  NULL
  ["status":"Cielo\Transaction":private]=>
  NULL
  ["authenticationUrl":"Cielo\Transaction":private]=>
  NULL
  ["authentication":"Cielo\Transaction":private]=>
  NULL
  ["authorization":"Cielo\Transaction":private]=>
  NULL
  ["merchant":"Cielo\Transaction":private]=>
  object(Cielo\Merchant)#329 (2) {
    ["affiliationId":"Cielo\Merchant":private]=>
    string(10) "1006993069"
    ["affiliationKey":"Cielo\Merchant":private]=>
    string(64) "25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3"
  }
  ["holder":"Cielo\Transaction":private]=>
  object(Cielo\Holder)#336 (6) {
    ["creditCardNumber":"Cielo\Holder":private]=>
    string(16) "4012001038443335"
    ["expiration":"Cielo\Holder":private]=>
    string(6) "201805"
    ["cvvIndicator":"Cielo\Holder":private]=>
    int(1)
    ["cvv":"Cielo\Holder":private]=>
    string(3) "123"
    ["holderName":"Cielo\Holder":private]=>
    string(14) "João da Silva"
    ["token":"Cielo\Holder":private]=>
    NULL
  }
  ["order":"Cielo\Transaction":private]=>
  object(Cielo\Order)#326 (8) {
    ["number":"Cielo\Order":private]=>
    string(14) "20150812000005"
    ["total":"Cielo\Order":private]=>
    int(1500)
    ["currency":"Cielo\Order":private]=>
    int(986)
    ["dateTime":"Cielo\Order":private]=>
    string(19) "2015-08-12T10:32:03"
    ["description":"Cielo\Order":private]=>
    NULL
    ["language":"Cielo\Order":private]=>
    string(2) "PT"
    ["shipping":"Cielo\Order":private]=>
    NULL
    ["softDescriptor":"Cielo\Order":private]=>
    NULL
  }
  ["paymentMethod":"Cielo\Transaction":private]=>
  object(Cielo\PaymentMethod)#325 (3) {
    ["issuer":"Cielo\PaymentMethod":private]=>
    string(4) "visa"
    ["product":"Cielo\PaymentMethod":private]=>
    int(2)
    ["installments":"Cielo\PaymentMethod":private]=>
    int(1)
  }
  ["returnURL":"Cielo\Transaction":private]=>
  string(46) "http://localhost:8080/ecommerce/api/cielo.html"
  ["authorize":"Cielo\Transaction":private]=>
  int(3)
  ["capture":"Cielo\Transaction":private]=>
  bool(true)
  ["freeField":"Cielo\Transaction":private]=>
  NULL
  ["bin":"Cielo\Transaction":private]=>
  string(6) "401200"
  ["generateToken":"Cielo\Transaction":private]=>
  bool(false)
  ["avs":"Cielo\Transaction":private]=>
  NULL
  ["token":"Cielo\Transaction":private]=>
  NULL
}

**Comment by davicrystal** [comment]
Olá Amigos,

Após diversos testes e investigações descobri um bug  no SDK que faz com que o XML enviado fique "malformado" fazendo com que o servidor sempre retorne o código de status http 400.

No arquivo CurlOnlyPostHttpClient.php, linha 16, a função que prepara a array para a variável $headers não considera a chave da array "mensagem: " que por sua vez então monta a string com o texto "mensagem: " mais o xml, fazendo com que o xml fique "malformado"

**O Exemplo abaixo, trata-se de um DUMP da variável $header após a função mencionada acima:**

> array(1) {
  [0]=>
  string(943) "mensagem: ```<?xml version="1.0" encoding="utf-8"?>
<requisicao-transacao xmlns="http://ecommerce.cbmp.com.br" id="20150814000015" versao="1.3.0"><dados-ec><numero>1006993069</numero><chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave></dados-ec><dados-portador><numero>4012001038443335</numero><validade>201805</validade><indicador>1</indicador><codigo-seguranca>123</codigo-seguranca><token/></dados-portador><dados-pedido><numero>20150814000015</numero><valor>1500</valor><moeda>986</moeda><data-hora>2015-08-14T15:51:32</data-hora><descricao/><idioma>PT</idioma><taxa-embarque>0</taxa-embarque><soft-descriptor/></dados-pedido><forma-pagamento><bandeira>visa</bandeira><produto>1</produto><parcelas>1</parcelas></forma-pagamento><url-retorno>http://digitalup.com.br</url-retorno><autorizar>3</autorizar><capturar>true</capturar><campo-livre/><bin>401200</bin><gerar-token>false</gerar-token></requisicao-transacao>```
"

**Comment by davicrystal** [comment]
Depois de novos testes e de verificar a documentação completa do webservice, verifiquei que os métodos mágicos __invoke nos arquivos src/Cielo/Http/CurlOnlyPostHttpClient.php e src/Cielo/Http/OnlyPostHttpClientInterface.php estavam com seus parâmetros invertidos e ao executar o método "CurlOnlyPostHttpClient" em src/Cielo/Http/CurlOnlyPostHttpClient.php, o "cabeçario" e "campos" para o Post, por estarem invertidos, construíam uma requisição "mal formada" que por sua vez gera a resposta "400 - Bad Request"

https://github.com/davicrystal/Webservice-1.5-php/commit/5e9a6c5dfed52121232921d45b254c0c2486e842

**Comment by wtabata** [comment]
@davicrystal éé estou nessa!! se eu conseguir algo aqui do um toke e mando um pull request vai q né!.

**Comment by davicrystal** [comment]
Olá @wtabata.

Já fiz um fork e arrumei! Se precisar use https://github.com/davicrystal/Webservice-1.5-php . Já mandei um pull request. Obrigado amigo!

**Comment by netojoaobatista** [comment]
Seu PR já foi mesclado, @davicrystal! Obrigado pela contribuição.

**Comment by wtabata** [comment]
@davicrystal @netojoaobatista showw!!

**Comment by wtabata** [comment]
@davicrystal fiz a atualização aqui e no meu caso continuou a mesma coisa. dando uma olhada em cada passo 

Cielo\Serializer\TransactionRequestSerializer
```
    public function serialize(Transaction $transaction)
    {
        [ ... ]
        return $document->saveXML();
    }

```

retorna uma "100699306925fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f34551870000000183201805112317814859910009862015-08-25T15:43:55PT0visa11http://localhost/payment3true455187false"

e não o bloco do xml e acaba requisição não funciona. se tiver alguma coisa em mente ae, serei grato.

**Comment by netojoaobatista** [comment]
Se você estiver vendo essa informação no browser, @wtabata, então esse é o comportamento esperado. O que acontece é que o browser tenta renderizar o XML, por isso a informação aparece toda truncada.

Tente fazer um `<Ctrl> + U` no browser, que você verá o XML em vez da tentativa de renderização.

**Comment by ciawebsite** [comment]
Estou tendo o mesmo problema a classe CurlOnlyPostHttpClient retorna apenas isso:

Cielo\Http\CurlOnlyPostHttpClient Object ( );

e acaba caindo em uma exception.

**Comment by wtabata** [comment]
@netojoaobatista @ciawebsite 
 Neto realmente fiquei tão querendo achar o problema que até esqueci do fonte.
Mas mesmo assim ainda está retornando em branco.

O que estava usando e o que estou usando agora.

Estava com PHP 5.5.3, troquei pra 5.6.12.
Achei q fosse problema na cURL mas está habilitada certinho
``` 
cURL support	enabled
cURL Information	7.42.1
```

Mas quando invoka CurlOnlyPostHttpClient, simplesmente não retorna nada e por isso o Warning: DOMDocument::loadXML():  e o UnexpectedValueException do \Cielo\Order.php:136

Estava usando ZF2, deixei de usar e testar apenas os arquivos, e mesmo assim, continua o problema.

O mais iincrivel fiz um test pelo Postman e o retorno veio com sucesso.!! Já não sei mais o que pode ser. Fiz print_r, var_dump de passo a passo, function por function!! Realmente para no retorno da cURL, que não vem nada.

Espero que alguem possa ter alguma ideia em como ajudar.

**Comment by CentaurWarchief** [comment]
@wtabata esses testes na versão são só unitários, eles não cobrem integração real no ambiente de testes da Cielo. Mas digo que seria uma boa ter esses para esses casos.

**Comment by dritec** [comment]
@davicrystal @wtabata @netojoaobatista @ciawebsite 
Estive debugando esse erro e me parece que ocorre quando o certificado da cielo não está configurado adequadamente no servidor. Até mesmo no servidor de homologação da cielo ocorre esse erro por conta dessa linha no curl curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, true);

Então acredito que é uma questão de configuração do certificado no servidor.
Testem trocando a linha para curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

**Comment by davicrystal** [comment]
Olá @dritec,

O problema desse ticket foi resolvido no fix davicrystal@5e9a6c5 ( @netojoaobatista , o que acha de fechá-lo? ), você tem razão sobre o certificado, ele precisa constar no "trustedstore" do servidor, portanto a melhor forma de resolver a questão do certificado é de fato seguir o procedimento disponibilizado na documentação da CIELO https://developercielo.github.io/Webservice-1.5/#certificado-digital  ( o link está incorreto na documentação, o domínio correto para o certificado é  https://ecommerce.cielo.com.br/ )

**Comment by netojoaobatista** [comment]
@dritec, você não deve fazer essa alteração no código; ela compromete a segurança da sua integração.

O certificado digital é um documento que garante a autenticidade da identidade da Cielo. Sem esse documento você não tem como saber se está efetivamente se comunicando com os servidores da Cielo. Imagine, por exemplo, que se houver um ataque *man-in-the-middle*, o certificado digital impede que você troque informações com um interceptador.

Por favor, siga os procedimentos descritos nesse link aqui: [https://developercielo.github.io/Checkout-Cielo/#certificado-extended-validation](https://developercielo.github.io/Checkout-Cielo/#certificado-extended-validation)

Instale o certificado em seu servidor e mantenha a verificação do certificado.

**Comment by wtabata** [comment]
@dritec como @davicrystal comentou, ja foi corrigido o problema!! e foi dado pull request já..  no meu caso, dava o mesmo erro por motivos obscuros que até hoje não sei o que é!!!. ficou dando problema foi troca php alteracao em todas as coisas da vida. e simplesmente um dia funcionou nem cheguei perto do certificado. ehhee. enfim!. o/ fazer o q
